defaults:
  - env: can
  - paths: paths
  - common
  - encoder: wan_vae
  - action_encoder: proprio
  - proprio_encoder: proprio
  - decoder: vqvae_wan
  - emb_decoder: linear
  - predictor: vit_wan
  - projector: resblock
  - override hydra/launcher: basic
  - _self_

ckpt_base_path: ${paths.data_root}/logs/experiments/tcwm_wan/${env_output_name:${env.name},${env.dataset_name}}
resume_folder: none
val_only: false
description: ""

latent_export:
  enabled: false
  output_path: null
  splits: ["train"]
  rgb_key: agentview_image
  latent_grid_size: 14
  mode: trajectory

hydra:
  run:
    dir: ${ckpt_base_path}/${now:%Y-%m-%d}/${now:%H-%M-%S}${maybe_suffix:${description}}
  sweep:
    dir: ${ckpt_base_path}/${now:%Y-%m-%d}/${now:%H-%M-%S}${maybe_suffix:${description}}
    subdir: ${hydra.job.num}

training:
  seed: 0
  epochs: 1
  batch_size: 1
  save_every_x_epoch: 1
  reconstruct_every_x_batch: 500
  num_reconstruct_samples: 2
  encoder_lr: 1e-6
  decoder_lr: 3e-4
  predictor_lr: 5e-4
  action_encoder_lr: 5e-4

env:
  dataset_name: walker-stand

has_predictor: True
has_decoder: True

encoder_emb_dim: 384
action_emb_dim: 32

proprio_emb_dim: 64

projected_dim: 128
compressed_patches: 49
original_patches: 196

alignment_dim: 64

model:
  _target_: models.visual_world_model.VWorldModel
  image_size: ${img_size}
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  train_encoder: False
  alignment_dim: ${alignment_dim}
  train_predictor: True
  train_decoder: True
  train_decoder_grad: False
  train_emb_decoder_grad: True
  projected_dim: ${projected_dim}

alignment:
  open_alignment: True
  state_consistency_loss_weight: 0.1
  alignment_regularization: 0.001
  latent_dynamics_loss_weight: 1.0

proprio_pred:
  loss_type: mse
  space: raw
  weight: 1.0
  infonce_temp: 0.1

video_save: true
video_save_every: 1
video_max_rollouts: 2
video_fps: null
video_resize: null
video_queue_size: 8
