name: mmbench
args: []
kwargs: {}

dataset_name: atari-alien #acrobot-swingup

dataset:
  _target_: "datasets.mmbench_dset.load_mmbench_slice_train_val"
  n_rollout: 200
  normalize_action: ${normalize_action}
  data_path: ${oc.env:MMBENCH_DATA_DIR,/mnt/data_nvme1/minghao.fu/newt_rollouts}/${env.dataset_name}
  image_size: ${img_size}
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16
