name: robomimic_tool_hang_full
args: []
kwargs:
  with_velocity: true
  with_target: true

dataset:
  _target_: "datasets.robomimic_dset.load_robomimic_slice_train_val"
  with_velocity: true
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: /data2/minghao/data/robomimic/tool_hang/ph_convert_full  # 完整43D proprio + 44D object = 87D states
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16
